# Simple workflow for deploying a static marimo notebook to GitHub Pages
name: Deploy Static Marimo App to GitHub Pages

on:
  # Runs on pushes to the main branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the necessary permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    name: Build Static HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install marimo jax jaxlib

      - name: Build static marimo app
        run: marimo export html your_notebook.py --output index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the generated index.html file
          path: "./index.html"

  # Deployment job
  deploy:
    name: Deploy to GitHub Pages
    # The deployment job needs the build job to be successful
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required for deployment
    permissions:
      pages: write
      id-token: write

    # Specify the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
